### ISSUE TITLE
Surface aspect angle for each triangle

### ISSUE THREAD

**Issue by osilan** [expertanalytics/rasputin#8]
Expected surface aspect angle for each triangle (gamma),
```0.0``` for slopes oriented South;
```-pi/2``` for slopes oriented East;
```pi/2``` for slope oriented West;
```+- pi``` for slopes oriented North;

smth like ```atan2(surface_normal(1),surface_normal(0))``` should work or pi-the same formula.

**Comment by skavhaug** [comment]
This is implemented now, but we let 0.0 be north, and positive toward east. So its a 180 degree rotation.
